### PR TITLE
add support for strix z690-a d4

### PR DESCRIPTION
**Pull request by ShadyNawara**
Hopefully, I made all the needed changes as I am getting the following error when trying to install the compiled module so I wasnt able to test it.

```
arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
  INSTALL /lib/modules/5.15.0-25-generic/extra/drivers/hwmon/asus-ec-sensors.ko
  SIGN    /lib/modules/5.15.0-25-generic/extra/drivers/hwmon/asus-ec-sensors.ko
At main.c:160:
- SSL error:FFFFFFFF80000002:system library::No such file or directory: ../crypto/bio/bss_file.c:67
- SSL error:10000080:BIO routines::no such file: ../crypto/bio/bss_file.c:75
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  /lib/modules/5.15.0-25-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
```
my motherboard does seem a bit different from your guide as this is all i have in my brec method. HWInfo and my other pull request to librehardware show that I have a Tsensor and a vrm sensor from the EC controller.
```
Method (BREC, 1, Serialized)
{
    Return (Ones)
    Return (Ones)
}
```

I attached my dsdt dat so you can double check

[dsdt-dsl.zip](https://github.com/zeule/asus-ec-sensors/files/8580095/dsdt-dsl.zip)

### CODE REVIEW

**Comment by zeule** [comment]
Thank you! I agree with the choice to use the SIO mutex and the rest of the code looks OK to me. You can try the module from the build directory (using `sudo insmod ./asus-ec-sensors.ko`). I know little about Ubuntu, which you seem to be using, but you probably follow [Gentoo wiki](https://wiki.gentoo.org/wiki/Signed_kernel_module_support#Building_the_kernel_with_proper_keys) and generate the signing key. I m going to submit these changes to the mainline kernel and thus I'd really want to get it tested, please.

**Comment by zeule** [comment]
> …so I wasnt able to test it.

You might try the DKMS way. If DKMS is available for your distribution, it should be able to build this module (`make dkms`).

**Comment by ShadyNawara** [comment]
I think the dkms method worked. how can I verify the new sensors worked though? hwinfo on windows only shows the vrm and t_sensor but I will check again.

**Comment by zeule** [comment]
> how can I verify the new sensors worked though?

Well, they should give non-zero output which varies with time, I guess, in `sensors` output (`sensors 'asusec-*'` to shorten the output).

**Comment by zeule** [comment]
Please add "Signed-off-by:" (git commit -s) if you want me to submit this change to the mainline kernel on your behalf.

**Comment by ShadyNawara** [comment]
can confirm the VRM and T_Sensor are reading correctly
I will try adding the other voltage sensors hwinfo is showing and fix the merge conflict as well
image

**Comment by ShadyNawara** [comment]
Any pointers on how to find the correct address for the VRM power sensors shown here?

image

**Comment by ShadyNawara** [comment]
Also I will go back and sign all commits once changes are finalized

**Comment by zeule** [comment]
> Any pointers on how to find the correct address for the VRM power sensors shown here?

The ec_sys module can give you a complete dump for all the EC registers in the bank 0 (`# hexdump -C /sys/kernel/debug/ec/ec0/io`). If you want to compare with the ASUS software or the HWINFO output, you can use [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/EC/EmbeddedController.cs) to run it in parallel with other monitoring apps.  The VRM current  and the "IVR TX VDDQ" seem to be two byte long each, so you need to test only even addresses. Other rational numbers are encoded in the EC registers as integers using small units, so the "IVR TX VDDQ" is probably no exception. Good luck finding these three sensors.

**Comment by ShadyNawara** [comment]
I have been investigating this for a while but I cant seem to get a reliable result. I tested every register using both the kernel driver and libre but I cannot get even close to the values HWinfo is showing. The numbers shown in hwinfo are inconsistent, in the screenshot above its showing the value going from 0 to 6912A for vrm current and i am getting similar results every time I run it. I checked Aida64 and its only showing the vrm and t_sensor sensors and nothing else. 

I made my recent changes in https://github.com/ShadyNawara/asus-ec-sensors/tree/vrm_sensors_wip if you want to take a look and here is the dump out of my ec_sys

  |   | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | A | B | C | D | E | F
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
30 |   | 0 | 0 | 0 | 0 | 0 | 0 | 24 | 0 | 0 | 0 | 38 | 24 | 1c | 1e | 29 | 0
40 |   | 7c | 40 | 24 | 5 | 0b | 0f | 0f | ff | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
50 |   | 0 | 0 | 0 | 24 | 0 | 0 | 0 | 0 | 0 | 24 | 0 | 0 | 0 | 0 | 0 | 0
60 |   | 0 | 0 | 0 | 3b | 39 | 0 | 0 | 0 | 0 | 0 | d8 | a9 | 0 | 0 | 0 | 0
d0 |   | 40 | 0 | 10 | 0 | 0 | 0 | 4 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 6



in the meantime I will sign the commits with the changes for vrm temp and t_sensors if you want to merge this for the time being.

**Comment by zeule** [comment]
Thank you! I'll submit it upstream.

**Comment by zeule** [comment]
Regarding those three sensors you want to locate, have you tried to find them in the second EC bank? Since they did not appear in older MB models, these new ones can be not in the first bank (like water temperatures for the AMD 500 serie).

**Comment by ShadyNawara** [comment]
That might be however my issue is that I am unable to get reliable results from other applications on windows so I have no reference for testing and the acceptable value range seems very large.

**Pull request merged**
