### PR TITLE
Add ROG STRIX X570-I

### PR DESCRIPTION
**Pull request by NickHu**
I've added support for ROG STRIX X570-I. It's very similar to the X570-E already supported, but has slightly different sensors.

hwinfo

I didn't add the sensor for "CPU Core Power", because I wasn't sure how to find its register or bank indices.

I've also attached the dsdt for examination.
[dsdt.zip](https://github.com/zeule/asus-ec-sensors/files/7721599/dsdt.zip)

### CODE REVIEW

**Comment by zeule** [comment]
Thank you! I've checked [the board specs](https://rog.asus.com/motherboards/rog-strix/rog-strix-x570-i-gaming-model/spec) and it seems strange to me that HWiNFO indeed shows so few sensors. ASUS specs state there is T_Sensor which usually is published via the EC. Then we have the chipset temperature sensor in every other model but not in this one? Could you test the chipset temperature sensor, please? I realise you might not have a thermistor to test the T_Sensor. Could you, please, look what sensors are provided by the ASUS software (AISuite)?

In Windows you can use LibreHardwareMonitor to quickly test your board, the EC part there is kind of similar to this driver.

**Comment by NickHu** [comment]
Here's a screenshot fro AISuite:
image

Here's another one from hwinfo:
image

LibreHardwareMonitor is only able to see the sensors from the Nuvoton NCT6798D, and doesn't report anything from the EC.

I don't remember if I plugged anything into that slot, but I suspect not.

**Comment by zeule** [comment]
Thank you (although the AISuite screenshots are not very useful because sensor panels are collapsed). So, this board seem to differ from other X570 ASUS boards I've seen before. As for the LibreHardwareMonitor I meant that you can easily add EC support yourself (look [here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/EC/EmbeddedController.cs#L50) and [here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/124fabb1951aebe59708b7f8050038b076ac79dd/LibreHardwareMonitorLib/Hardware/Motherboard/Identification.cs#L185)). 

Anyway, I think we can enable the T_Sensor entry for this board. Could you, please, do that and test? For other boards it returns a blank value of 216 with the thermistor unconnected. As for the CPU power, I believe it is computed using the reading for CPU current and the Vcore from the Nuvoton chip.

**Comment by zeule** [comment]
Thanks!

**Comment by NickHu** [comment]
I can confirm that it reports 216 (T_Sensor unconnected). By the way, should this change be backported to the older asus-wmi-ec-sensors in the kernel?

**Comment by zeule** [comment]
> I can confirm that it reports 216 (T_Sensor unconnected). 

Splendid, thanks!

> By the way, should this change be backported to the older asus-wmi-ec-sensors in the kernel?

I'm about to submit this driver to the mainline instead.

**Pull request merged**
