### PR TITLE
Add support for ProArt X670E-CREATOR WIFI

### PR DESCRIPTION
**Pull request by KeithMyers**
Add support for ProArt X670E-CREATOR WIFI

### CODE REVIEW

**Comment by zeule** [comment]
Thanks you! Would it be possible for you, please, to provide a single signed off (`-s` option for `git commit`) commit, which then could be forwarded to the mainline kernel? Otherwise I would not be able to submit the changes in your name.

**Comment by KeithMyers** [comment]
Sure as soon as I figure out how to do that.  Very much a newbie in using Github to actually change and submit code changes.

**Comment by zeule** [comment]
I enabled the requirement to sign-off commits for web contributions for this repository. Might help if you create yet another PR.

**Comment by KeithMyers** [comment]
Oh great . . . now I have to figure out how to do a PR all over again.
I assume what I did was not correct or sufficient?

**Comment by zeule** [comment]
Let me repeat, please: if you want your changes to be submitted to the mainline kernel with your name in them, I need a single signed off commit. Otherwise I will create such a commit myself and sign it off (and add a link to this PR).

**Pull request merged**
